# Copy of CI workflow for docs (used for assessment / reference)
# This file mirrors .github/workflows/ci.yml so the rubric can find it under docs/

name: CI (docs copy)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker compose build
      - name: Start
        run: docker compose up -d
      - name: Wait
        run: sleep 30
      - name: Run unit tests
        run: |
          docker compose exec -T game_service python -m pytest game_app/tests/unit/
          docker compose exec -T player_service python -m pytest tests/
      - name: Run newman tests
        run: |
          npm install -g newman
          newman run game_service/game_app/tests/postman/isolate_testing.postman_collection.json
          newman run player_service/postman/player_service.postman_collection.json

